Dao-AILab/flash-attention

setup.py
Quick PR addressing two minor issues I encountered while installing `flash-attention`:
1. Adds the `einops` dependency to `setup.py` such that it's installed automatically along with the package.
2. Adds `__init__.py` to the `flash_attn` package such that `setup.py` properly detects it. Before, `flash_attn` could not be imported from outside of the `flash-attention` directory, even after the `setup.py` installation.
=> Slightly improve installation process

csrc/flash_attn/src/fmha_dgrad_fp16_kernel_loop.sm80.cu, csrc/flash_attn/src/fmha_fprop_fp16_kernel.sm80.cu, csrc/flash_attn/src/fp16_switch.h, setup.py
This should resolve #50.
I was able to compile with CUDA 11.6, PyTorch 12.1 + CUDA 11.6, and an RTX 3090 as the target.
I haven't run any checks to see if the results are correct, is there any scripts for this purpose?
I was able to run the benchmark and saw big improvements in speed (~1/5 the time for forward + backward)
Hopefully someone else can also try to compile with this fork and see if it works for them.  Maybe @C43H66N12O12S2 would be interested in trying?
Also, huge thanks to @C43H66N12O12S2 to narrowing down the cause to "MSVC quirks with std::conditional" and C++17 being needed for the compiler, with that I was able to find the issue.
=> Make flash attention compile on Windows.

.github/workflows/publish.yml
Hi, @tridao , I notice that the recent [`GitHub actions`](https://github.com/HazyResearch/flash-attention/actions/runs/3260714185) failed due to the workflow can not get the release to upload the wheel. But in my forked repo, it's ok to [build the wheel and upload to the release](https://github.com/robotcator/flash-attention/actions/runs/3263863115), and the wheel can be seen on the [release page](https://github.com/robotcator/flash-attention/releases/tag/refs%2Fheads%2Fmain). 
It's a little bit wired, I change to `push trigger` on a certain branch to `tag create trigger` in this pr. The workflow works as follows, we create the tag for the recent commit, and then this action will trigger the GitHub action to build the wheel and upload the build wheel to release page, we can download the …
=> build wheel and upload to release

usage.md
Now that flash attention is being used to train all future gpt-neox models, we should display it as an example adoption framework.
=> Add gpt-neox adoption

flash_attn/flash_attention.py
Documentation says default is 0.1, but the code has attention_dropout default at 0.0
=> Change default dropout value in documentation

flash_attn/flash_attention.py
I noticed that there were kwargs specified in the FlashAttention implementation to mirror PyTorch (device, dtype), but they weren't used.  This is a little confusing when you're first reading the code.
I can see an argument for leaving them in (to mirror PyTorch), but I can also see an argument for removing them, so they don't mislead users into thinking they do something.
I modified FlashMHA to not pass in the factory kwargs.  I removed the kwargs argument in this class as well, since it wasn't being used.
I'll leave it to you to decide if this makes sense or not.
=> Remove unused kwargs like device in FlashAttention

flash_attn/flash_attn_interface.py
The `_flash_attn_backward` function is non-deterministic as noted [here](https://github.com/HazyResearch/flash-attention/issues/73#issuecomment-1312814265) previously, however setting `num_splits=1` ensures deterministic behavior at the cost of some performance. This PR adds a boolean argument (`deterministic`) to the Python APIs to optionally enable this. The default is still `False` in order to keep the current behavior and perf unchanged.
I have verified that all tests under `tests/test_flash_attn.py` are passing.
=> Add option for deterministic execution

setup.py
Hi, have this message using pypi version
```
Collecting flash-attn
Downloading flash_attn-1.0.1.tar.gz (1.9 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 371.5 kB/s eta 0:00:00
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'error'
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [6 lines of output]
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File "/tmp/pip-install-n2wuvsgw/flash-attn_a2bf946cac174b0fab99cbff2ad5f6e6/setup.py", line 6, in <module>
from packaging.version import parse, Version
ModuleNotFoundError: No module named 'packaging'
[end of output]
```
=> Missing module in `setup.py`

csrc/flash_attn/fmha_api.cpp, csrc/flash_attn/src/fmha.h, csrc/flash_attn/src/fmha_dgrad_kernel_1xN_loop.h, csrc/flash_attn/src/fmha_fprop_kernel_1xN.h, flash_attn/flash_attn_interface.py
Fixes #165 
To ensure that the same dropout mask is drawn during backprop as in the fprop execution, currently, the cuda RNG state is saved during the forward pass and then reset during backward. This is done in PyTorch via the `torch.cuda.{get|set}_rng_state` APIs. However, this breaks graph execution since querying or setting the internal seed is prohibited, along with other CPU ops. To bypass these calls while maintaining correct behavior (and enable graph execution), we can save the seed and offset values as GPU tensors in the forward kernels after unpacking the philox RNG state. These can be reused in the backward pass to correctly initialize the `Philox` class with the correct seed and offset without needing to reset the RNG or calling `philox_cuda_state` on the generator (during …
=> Enable CUDA graph capture

flash_attn/models/gpt.py, flash_attn/modules/block.py
Simple fixes to avoid `cannot unpack non-iterable NoneType object` upon `ImportError` - bug found during a debugging session with @massastrello
=> [BugFix] avoid bug on ImportError

README.md, pyproject.toml
This PR introduces a `pyproject.toml` file to list the build dependencies (see https://snarky.ca/what-the-heck-is-pyproject-toml/).
Before, the build dependencies were listed in `setup.py`, but in order to read this file, you would need to have those dependencies installed (packaging, torch). By adding a `pyproject.toml` file, python knows which packages are needed to build flash-attention.
=> Use pyproject.toml to specify build dependencies

pyproject.toml
There is a significant bump in compilation time going from `v1.0.4` &rarr; `v1.0.5`. It was ~2-3 minutes previously and now ranges from ~17-40 minutes. I did a bisect and narrowed it down to extra dependencies being required in the `pyproject.toml` file which are already set in the `install_requires` section during setup. I've left the `packaging` library as is in `[build-system]` since it's used by `setup.py` itself.
=> Fix compilation time

flash_attn/layers/rotary.py
This resolves RuntimeErrors after running evaluation in inference mode and starting a new training phase:
```
File "/home/proger/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/home/proger/.local/lib/python3.10/site-packages/flash_attn/modules/mha.py", line 492, in forward
qkv = self.rotary_emb(qkv)
File "/home/proger/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/home/proger/.local/lib/python3.10/site-packages/flash_attn/layers/rotary.py", line 229, in forward
return apply_rotary_emb_qkv_(
File "/home/proger/.local/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
return super().apply(*args, …
```
=> rotary: update cos/sin cache when switching from inference mode

usage.md
A [500-line implementation](https://github.com/philipturner/metal-flash-attention/blob/main/Sources/Attention.metal) of FlashAttention, and the first that does not require CUDA.
It has now passed an initial validation test (R=33, C=15, H=3, D=27, dense FP16), so it can be classified as a working FlashAttention implementation.
<details>
<summary>Head 0</summary>
</details>
<details>
<summary>Head 1</summary>
</details>
<details>
<summary>Head 2</summary>
</details>
cc @liuliu
=> Metal FlashAttention

csrc/flash_attn/src/static_switch.h
See also: https://stackoverflow.com/questions/55136414/constexpr-variable-captured-inside-lambda-loses-its-constexpr-ness
We had this sort of errors with nvcc 11.6:
```
$SRC_DIR/third_party/flash-attention/csrc/flash_attn/src/flash_fwd_launch_template.h(68): error: expression must have a constant value
Note #2767-D: the value of *this cannot be used as a constant
detected during instantiation of "void run_mha_fwd_hdim64<T>(Flash_fwd_params &, cudaStream_t) [with T=cutlass::half_t]" 
$SRC_DIR/third_party/flash-attention/csrc/flash_attn/src/flash_fwd_hdim64_fp16_sm80.cu(25): here
```
=> Fix compile error with `BOOL_SWITCH`

training/Dockerfile
The repo doesn't have `v2.0.0.post1` branch anymore. 
Remove it so the docker image can be built.
=> remove checkout v2.0.0.post1 from dockerfile

csrc/layer_norm/ln_api.cpp
Fixes #314 
See #314. Moving the `launcher` call ensures `params.rows` is defined and fixes the counter value, I think it shouldn't have any other effect.
Running the script
```
import torch
import dropout_layer_norm
kwargs={"device":"cuda", "dtype":torch.float16}
d=4096
torch.cuda.init()
torch.cuda.manual_seed(0)
gen=torch.cuda.default_generators[torch.cuda.current_device()]
print("START",gen.get_state()[-8:].tolist())
x=torch.randn([d,d], **kwargs)
r=torch.randn([d,d], **kwargs)
gamma=torch.randn([d], **kwargs)
beta=torch.randn([d], **kwargs)
print("BEFORE DROPOUT LN",gen.get_state()[-8:].tolist())
y1, *rest = dropout_layer_norm.dropout_add_ln_fwd(
x, r, gamma, beta, None, None, None, None, 0.1, 1e-5,
1.0, 0, None, False, False
)
print("AFTER DROPOUT LN 1",gen.get_state()[-8:].tolist()) …
```
=> Fix random state for dropout_layer_norm

csrc/flash_attn/flash_api.cpp, csrc/flash_attn/src/flash.h, csrc/flash_attn/src/flash_bwd_kernel.h, csrc/flash_attn/src/flash_fwd_kernel.h, flash_attn/flash_attn_interface.py
Fixes #379 
Flash attention 2 broke the CUDA graphs support that was previously added, this PR mostly re-implements the changes in #166 (that PR description explains the changes) in order to enable CUDA graph capture.
All tests under `tests/test_flash_attn.py` are passing except few race condition checks that fail even outside this PR.
=> Enable CUDA graphs

flash_attn/models/gpt.py, flash_attn/models/llama.py, tests/models/test_llama.py
Create a function that maps a `state_dict` for standard GPT model for llama back to hugging face format. 
There are more line changes than I intended since I ran black and isort on the test file.
=> map custom model state_dict back to huggingface format

flash_attn/bert_padding.py
A new `unpad_input_for_concatenated_sequences` function is created to replace `unpad_input` in `flash_attn/bert_padding.py`. 
It helps to support concatenating short samples in one for efficient training, which is discussed in https://github.com/Dao-AILab/flash-attention/issues/432#issuecomment-1668822286.
=> add unpad_input_for_concatenated_sequences

README.md
Very minor, but the Flash Attention 2 citation was missing a closing brace on the title (resulting in an error when copy/pasting into a paper 🙂 )
=> fix citation in README

flash_attn/ops/fused_dense.py
when using checkpoint_lvl=2, we all_gather_raw(x) without async_op=True. 
So we don't need to wait for handle. Just skip.
=> [bugfix] handle_x not define when using checkpoint_lvl = 2

.gitignore, flash_attn/models/bert.py, tests/models/test_bert.py
Adds an `inv_remap_state_dict` function that will convert flash_attn BERT models back to a HF-compatible state_dict
=> Convert flash_attn BERT models back to HuggingFace format

flash_attn/models/bert.py, flash_attn/models/bigcode.py, flash_attn/models/gpt.py, tests/models/test_bert.py, tests/models/test_bigcode.py
Implements bidirectional conversion for the BigCode series of models (e.g. StarCoder, WizardLM) along with corresponding unit tests.
Also adds `gelu_pytorch_tanh` to the list of supported activation functions (see https://github.com/huggingface/transformers/blob/95b374952dc27d8511541d6f5a4e22c9ec11fb24/src/transformers/activations.py#L28-L46), since `gelu_new` and `gelu_fast` are equivalent to `nn.GELU(approximate='tanh')`
=> BigCode model converters

setup.py
As title says, very minor addition to `setup.py` error message. It took me some time to realize that the `nvcc` version being used was actually still an old one on one server (even though the driver had CUDA 12.2 as shown in `nvidia-smi`) 😅 
[Stackoverflow Reference](https://stackoverflow.com/questions/53422407/different-cuda-versions-shown-by-nvcc-and-nvidia-smi)
=> [Minor] add nvcc note on bare_metal_version `RuntimeError`

flash_attn/models/llama.py, tests/models/test_llama.py
The current `permute` methods used in loading/unloading Llama weights do not map key weights correctly when MQA/GQA is used. This PR patches this bug and adds a corresponding test to validate.
=> Fix Llama GQA/MQA

flash_attn/layers/rotary.py
There are two bugs in the backward pass of ApplyRotaryEmbQKV_ which this PR fixes. One is that `interleaved` was not defined, it should be `ctx.interleaved`. The other is that "conjugate" is misspelled.
=> Fix NameError and typo in ApplyRotaryEmbQKV_

csrc/flash_attn/flash_api.cpp, csrc/flash_attn/src/block_info.h, csrc/flash_attn/src/flash.h, flash_attn/flash_attn_interface.py
Add a new argument `seqused_k` to varlen_fwd / mha_varlen_fwd . By supplying a tensor (instead of None/nullptr), a user can indicate how many of the keys in each batch element should actually be attended to. This allows k and v to contain padding.
=> Allow varlen_fwd to take optional seqused_k

csrc/flash_attn/flash_api.cpp
This PR speeds up decoding attention when lengths are variable within the batch, by adding two optimizations (split-kv and M<->H swap), which were already present on non-variable-length path. 
It also refactors logic for setting split-kv-related parameters into a separate function `set_params_splitkv`.
```
pytest -k test_flash_attn_varlen tests/test_flash_attn.py 2>&1 | tee log.txt
platform linux -- Python 3.9.18, pytest-7.4.4, pluggy-1.3.0
rootdir: /home/grigorysizov/flash-attention
collected 367460 items / 312356 deselected / 55104 selected
tests/test_flash_attn.py ............................................... [  0%]
...
.................................................                        [100%]
============= 55104 passed, 312356 deselected in 771.03s (0:12:51) =============
``` …
=> Add split-kv and M<->H swap to varlen forward decoding attention

README.md, flash_attn/flash_attn_interface.py
The `block_table` should be `(batch_size, max_num_blocks_per_seq)`.
=> Fixes an error in comment: the `block_table` should be `(batch_size, max_num_blocks_per_seq)`

flash_attn/bert_padding.py
Updated docstring for `unpad_input()` to include missing `indices` return.
Updated docstring for `unpad_input_for_concatenated_sequences()` to include missing `indices` return.
Updated docstring for `pad_input()` to include more detailed description of `indices` argument and include missing `batch` and `seqlen` arguments.
=> Updated missing docstrings for args and returns in bert_padding.py

.github/workflows/publish.yml
Add PyTorch 2.3 (dev/nightly) to CI build matrix.
Resolves #790
=> [CI] Build wheels for Pytorch 2.3 (dev/nightly)

csrc/flash_attn/flash_api.cpp, csrc/flash_attn/src/flash_bwd_launch_template.h, csrc/flash_attn/src/flash_fwd_launch_template.h, csrc/flash_attn/src/static_switch.h
For faster and smaller builds in some simple cases, provide switches to allow disabling
* backward
* alibi
* uneven k
* dropout
* local attention
Note that the error checking here depends on the C++ preprocessor definitions, and most of the implementation depends on the nvcc preprocessor definitions, so I am assuming users will set them the same in both places.
cc @drisspg @danthe3rd @sgrigory
=> Preprocessor switches to control functionality

csrc/flash_attn/flash_api.cpp
Fix build error reported in https://github.com/Dao-AILab/flash-attention/issues/814
I don't have a way to test this on Windows, but @bottler pointed out that `long` keyword is the likely problem. Is there a way to run Windows CI on this PR? @tridao
=> Fix Windows build

csrc/flash_attn/flash_api.cpp
I added more details at https://github.com/pytorch/pytorch/pull/119500. But the repro I went off of is pasted below, and the case that is affected is when `key` is contiguous but `value` is not:
```
import torch
a = torch.randn(2, 513, 16, 64, dtype=torch.float16, device='cuda').transpose(1, 2)
b = torch.randn(2, 16, 513, 64, dtype=torch.float16, device='cuda')
c = torch.randn(2, 16, 513, 64, dtype=torch.float16, device='cuda')
d = torch.randn(2, 513, 16, 64, dtype=torch.float16, device='cuda').transpose(1, 2)
e = torch.randn(2, 16, 513, 64, dtype=torch.float16, device='cuda')
f = torch.randn(2, 16, 513, device='cuda')
g = None
h = None
i = 513
j = 513
k = 0.0
l = False
m = torch.tensor(1, dtype=torch.int64)
n = torch.tensor(1, dtype=torch.int64)
out1_ref, out2_ref, out3_ref = …
```
=> fix backward for when query and key have different contiguity

setup.py
Flash-attn takes a lot of ram and cpu cores to compile. Most users do not have 64 cores or over 96GB of ram and hand adjusting MAX_JOBS is trial-and-error and not to mention a waste of dev time. 
Problem this PR attempts to solve:
1. Ninja MAX_JOBS is unaware of threads=4 spawned by nvcc. 
2. Ninja MAX_JOBS is unaware of actual available memory in environment
3. Both 1 and 2 combined results in oom, heavy swap usage, oversubscribed threads to core count (thread starvation) and general reduced efficiency in compiling since ninja is not resource aware. 
Without this PR, `python setup install` will OOM on an Intel 14700k consumer machine with 96GB of ram (swap disabled). Using readme recommended MAX_JOBS=4 will lead to very slow compilation.  Both options are sub-optimal. This led to the …
=> Fix common compilation issues by auto-adjusting ninja MAX_JOBS env var

setup.py
This change allows flash attention to be built for the new NVIDIA GH 200 platform (aarch64).
=> Support ARM builds

csrc/flash_attn/flash_api.cpp, flash_attn/flash_attn_interface.py, tests/test_flash_attn.py
Paged attention was added recently in https://github.com/Dao-AILab/flash-attention/commit/54e80a3829c6d2337570d01e78ebd9529c02d342, but only exposed through `fwd_kvcache`. This PR exposes it though `varlen_fwd`.
@bottler @danthe3rd
Tests:
```
pytest  tests/test_flash_attn.py -k test_flash_attn_varlen_causal 2>&1 | tee log.txt
```
```
collected 420068 items / 417188 deselected / 2880 selected
tests/test_flash_attn.py ............................................... [  1%]
........................................................................ [  4%]
...
........................................................................ [ 99%]
.........................                                                [100%]
=================== 2880 passed, 417188 deselected in 50.32s =================== …
```
=> Enable paged attention in varlen forward

flash_attn/modules/mha.py
This PR addresses https://github.com/Dao-AILab/flash-attention/issues/845. Since the `MHA` module may be cast to fp16 or bf16, but the `alibi_slopes` buffer should be fp32, we cast them to that precision in `forward`.
=> Cast the alibi slopes to torch.float32

flash_attn/ops/triton/rotary.py, tests/test_rotary.py
All integer parameters in Triton kernels are [specialized](https://github.com/openai/triton/blob/release/2.2.x/python/triton/runtime/jit.py#L180) by default, meaning that (for the `2.2` version of Triton) a different kernel will be generated for the following mutually exclusive classes of parameter values:
* divisible by 16
* divisible by 8, but not by 16
* not divisible by either 8 or 16, and not equal to 1
* equal to 1
`nheads` and `CACHE_KEY_SEQLEN` are not used at all in `rotary_kernel`, but they still trigger re-compilation whenever their values move between classes. This is doubly ironic given that the comment in the code indicates that `CACHE_KEY_SEQLEN` was meant to `limit number of compilations` (probably when it was used for autotuning?).
I removed the unused parameters and …
=> Fix spurious re-compilations of `rotary_kernel`

setup.py
Set `packaging` and `ninja` as build time dependencies rather than runtime dependencies.
Xref https://github.com/conda-forge/staged-recipes/pull/26239#discussion_r1590048101 where we're trying to package `flash-attn` on conda-forge, and would like the setup.py metadata to be correct so that running `pip check` would work.
=> Move packaging and ninja from install_requires to setup_requires

csrc/flash_attn/flash_api.cpp, csrc/flash_attn/src/flash.h, csrc/flash_attn/src/flash_bwd_kernel.h, csrc/flash_attn/src/flash_bwd_preprocess_kernel.h, csrc/flash_attn/src/flash_fwd_kernel.h, flash_attn/flash_attn_interface.py, tests/test_flash_attn.py
Closes https://github.com/Dao-AILab/flash-attention/issues/725
For variable seqlen case, keep LSE in `(H, total_q_seqlen)` format instead of current `(B, H, max_q_seqlen)`. This helps to save memory when variance of sequence length within the batch is large, e.g. during long sequence training. 
Based on https://github.com/GD06/flash-attention/pull/2
```
pytest tests/test_flash_attn.py 2>&1 | tee ~/log_on_branch.txt
...
============= 268004 passed, 152064 skipped in 4382.92s (1:13:02) ==============
```
Full output: https://gist.github.com/sgrigory/c95d8bdcd87721a60fb51f8c02be0f6b
cc @GD06 @jianyuh
=> Support unpadded LSE layout

csrc/flash_attn/src/flash_fwd_kernel.h
This PR removes swizzle part of `sV.data()` to get a completely non-swizzled `sVtNoSwizzle`, or `sVtNoSwizzle` would contain a swizzled base smem ptr derived from
```
Tensor sV = make_tensor(sK.data() + size(sK), typename Kernel_traits::SmemLayoutKV{});
```
<br/></br>
corresponding source code in cutlass:
```
// A flagged construction method to transform ComposedLayout
// Make a swizzle pointer tensor and check that the intended type size matches
template <class Iterator, class SwizzleFn, int B, class Layout>
CUTE_HOST_DEVICE constexpr
auto
make_tensor(Iterator const& ptr,
ComposedLayout<SwizzleFn,smem_ptr_flag_bits<B>,Layout> const& layout)
{
static_assert(is_smem<Iterator>::value, "Expected smem.");
static_assert(B == sizeof_bits<iter_value_t<Iterator>>::value, "Expected a B-bit pointer …
```
=> remove swizzle part of `sV.data()` to get a completely non-swizzle `sVtNoSwizzle`

csrc/flash_attn/flash_api.cpp
When user send `out` as a parameter of the function
`seqlenq_ngroups_swapped` with parameters that trigger,
the CHECK_SHAPE is incorrect (since q shape is modified.)
=> Fixing argument checking when using `seqlenq_ngroups_swapped`.

csrc/flash_attn/src/alibi.h, csrc/flash_attn/src/flash_bwd_kernel.h, csrc/flash_attn/src/mask.h
I think there is a typo about the shape. Since after `flash::convert_layout_acc_rowcol` we got `(nrow=(2, MMA_M), ncol=(2, MMA_N))`.
And we use the second dim `size<1>` to get col idx.
```c
for (int nj = 0; nj < size<1, 1>(tensor); ++nj) {
const int col_idx_base = col_idx_offset + nj * 8;
#pragma unroll
for (int j = 0; j < size<1, 0>(tensor); ++j) {
const int col_idx = col_idx_base + j;
```
So change `(ncol=(2, MMA_M), nrow=(2, MMA_N))` to `(nrow=(2, MMA_M), ncol=(2, MMA_N))`.
=> Fix typos of statement about shape.

csrc/flash_attn/flash_api.cpp, csrc/flash_attn/src/flash.h, csrc/flash_attn/src/flash_fwd_kernel.h, csrc/flash_attn/src/flash_fwd_launch_template.h, csrc/flash_attn/src/static_switch.h, flash_attn/flash_attn_interface.py, setup.py, tests/test_flash_attn.py
Quick&dirty implementation (but seems functional).
Fixes #1016
=> [WIP] First draft for softcapping.

flash_attn/flash_attn_interface.py, hopper/flash_attn_interface.py
Hi, team, thanks for the great work of flash attention!
I'm working on the [vLLM project](https://github.com/vllm-project/vllm), and we use flash-attention a lot.
Recently, I'm investigating `torch.compile` integration, and I find these lambda functions will annoy `torch.compile`, which can generate irregular Python bytecode.
Moving these lambda functions into a normal function can fix the problem.
=> remove lambda in interface

hopper/flash.h, hopper/flash_bwd_launch_template.h, hopper/flash_fwd_launch_template.h, hopper/utils.h
These make it so external C++ libraries can include `flash.h` without needing to depend on torchlib. The use case here is including FA3 in other C++ codebases, usually by either git submodules or CMake fetchcontent. Obviously `flash_api.cpp` needs to include torchlib to provide the torch interface, but the call stack below that can be done without needing it.
Changes are mainly just using native CUDA check macros rather than the ones from ATen. Another thing is I had to delete `philox_args` from `Flash_fwd_params`, which wasn't being used anywhere currently. If you have to add this back in at some point I hope it could be done without reintroducing the torchlib dependency.
=> [FA3] Remove torchlib dependency from cpp files (except flash_api.h)

hopper/setup.py
Library name to import is `flash_attn_interface`, which matches the test.
This makes it easier to experiment with FA3 as a library.
=> Make FA3 externally importable

flash_attn/modules/mha.py
In FlashCrossAttention, `isinstance(max_seqlen, int)` is executed twice, but `max_seqlen_k` is not checked
=> Fix: check the type of max_seqlen_k instead of checking max_seqlen twice

README.md
The current README has two `Installation and Features` sections (one for "normal" flash attention with CUDA backend) and one for AMD GPUs. Both `Installation and Features` were at header level 2, and the `AMD GPU Support` section was arbitrarily far down away from the other installation instructions. The AMD installation instructions also failed to mention `packaging` and `ninja` as requirements.
This updated README consolidates CUDA and ROCm backends under the single `Installation and Features` section near the top.
=> Clearer install instructions for CUDA and ROCm backends

hopper/benchmark_flash_attention_fp8.py, hopper/flash.h, hopper/flash_api.cpp, hopper/flash_attn_interface.py, hopper/flash_fwd_kernel.h, hopper/flash_fwd_launch_template.h, hopper/kernel_traits.h, hopper/mainloop_fwd_sm90_tma_gmma_ws.hpp, hopper/softmax.h, hopper/test_flash_attn.py
This PR adds qkv descales for the fp8 kernel, added warpgroup sync in producer in do_transpose_V lambda, and slightly altered schedule for h128 causal fp8 that allows for using max offset to fill fp8 range before 2nd gemm with minimal perf penalty (<10 tflops measured on my H100 PCIe, log attached).
[new_fp8_h128_times_0823.log](https://github.com/user-attachments/files/16734356/new_fp8_h128_times_0823.log)
=> FA3 FP8 qkv descales + restore max offset for h128 causal + added sync for producer WG

hopper/flash_bwd_launch_template.h, hopper/flash_bwd_postprocess_kernel.h, hopper/flash_bwd_preprocess_kernel.h
Certain versions of CUTLASS are having compiler errors related to the additional backwards kernels not having an `ArchTag` defined. When you launch the kernel it will check this type for feature compatibility. I'm compiling with a different CUTLASS version, but when FA updates its version errors will start appearing too. These changes just copy the semantics from [`CollectiveMainloopBwd`](https://github.com/Dao-AILab/flash-attention/blob/c92ca63268836a6ea519e9892eda4895fc31811d/hopper/mainloop_bwd_sm90_tma_gmma_ws.hpp#L37) into the pre and postprocess bwd kernels.
=> Add ArchTag to pre/postprocess bwd kernels

README.md, setup.py
As `__grid_constant__` was introduced in CUDA 11.7, the minimal supported CUDA version must change from `11.6` to `11.7`. The project is failed to build from tag `v2.4.0` with CUDA 11.6 and shows the errors as follow. (I just test building from the latest tag back to `v2.4.0`, which does not mean older versions can pass.)
```
/usr/local/cuda/bin/nvcc -I/workspace/flash-attention/csrc/flash_attn -I/workspace/flash-attention/csrc/flash_attn/src -I/workspace/flash-attention/csrc/cutlass/include -I/usr/local/lib/python3.8/dist-packages/torch/include -I/usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.8/dist-packages/torch/include/TH -I/usr/local/lib/python3.8/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.8 …
```
=> feat: change minimal supported CUDA version to 11.7

hopper/flash_attn_interface.py
This PR adds `descale_q`, `descale_k`, and `descale_v` to FA3 interface `flash_attn_func` in `hopper/flash_attn_interface.py`. It did not add those descales to `flash_attn_varlen_func` as testing shows there are some issues with that code path.
=> Add q, k, v descales to FA3 interface

csrc/flash_attn/flash_api.cpp, flash_attn/flash_attn_interface.py
This PR adds basic support for torch.compile() for the non-varlen variants of Flash Attention.
This essentially allows for models that use the `flash_attn_qkvpacked_func`, `flash_attn_kvpacked_func`, and `flash_attn_func` to compile without graph breaks.
I can add unit tests if it makes sense. I'll test it with our own training pipeline for performance measurements and I'll post them later.
This uses the new custom operators API in Pytorch 2.4. I can move to the older APIs if needed, or I can look up how to make both coexist
=> Add custom ops for compatibility with PT Compile

hopper/setup.py
This PR fixes FAv3 compilation with MSVC.
There are 2 issues:
- `-D_USE_MATH_DEFINES` is needed for [Math constants](https://learn.microsoft.com/en-us/cpp/c-runtime-library/math-constants?view=msvc-170) in MSVC, specifically `M_LN2` used in `hopper/softmax.h`.
- `-Xcompiler=/Zc:__cplusplus` sets `__cplusplus` correctly, in turn this enables `CUTLASS_CONSTEXPR_IF_CXX17` in Cutlass which is used by `cutlass::gcd`.
These options are added to `nvcc_flags` when `get_platform() == "win_amd64"`.
=> Fix FAv3 compilation with MSVC

csrc/flash_attn_ck/flash_api.cpp, csrc/flash_attn_ck/mha_bwd.cpp, csrc/flash_attn_ck/mha_fwd.cpp, csrc/flash_attn_ck/mha_varlen_bwd.cpp, csrc/flash_attn_ck/mha_varlen_fwd.cpp
I found python api (flash_api) has changed by @ani300 in [PR#1139](https://github.com/Dao-AILab/flash-attention/pull/1139)
Sync the number of return value in this PR.
=> Sync api change for ROCm Flash attention

.github/workflows/publish.yml
PyTorch 2.5 has just been released: https://pytorch.org/blog/pytorch2-5/
It supports cuda 11.8->12.4
I also changed PyTorch 2.4 to support cuda 12.4 too
=> Feat: Add support for PyTorch 2.5 in workflows

hopper/copy_paged_sm90_tma.hpp, hopper/flash.h, hopper/flash_api.cpp, hopper/flash_attn_interface.py, hopper/flash_fwd_launch_template.h, hopper/mainloop_fwd_sm90_tma_gmma_ws.hpp, hopper/seq_len.h, hopper/static_switch.h, hopper/test_flash_attn.py
Adding support for Paged Attention / block table to the Flash-Attention 3 Kernel.
Limits:
- ~~Not yet integrated with #1236 which modifes the same code (and more).~~
- No fp8 support yet - as that support also seems missing in the non-paged varlen version so far.
Test Plan:
```
cd hopper
pytest test_flash_attn.py -k "test_flash_attn_varlen_paged"  -s
```
**Update**
- Rebased on top of main, which includes #1236 now
- Original version of this PR ( not rebased ) still available on [this branch](https://github.com/kadeng/flash-attention/tree/fa3-paged-original)
=> Paged Attention support for FA3

.github/workflows/publish.yml, setup.py
Very recently, a pull request was merged to add PyTorch 2.5 support (https://github.com/Dao-AILab/flash-attention/pull/1284)
However, this pull request seems to have accidentally broken the build system, which I uncovered when trying to build wheels for PyTorch 2.5.
The problem is that the build system builds with CUDA 12.3, but PyTorch doesn't have any 12.3 
releases. See https://github.com/EthanSteinberg/flash-attention/actions/runs/11762473443/job/32765408364#step:8:56 for the failed run.
This PR simply changes the build system to build against 12.4.1 instead.
As an aside, if this PR gets accepted, I would really appreciate if you can do a flash-attention 2.6.4 release that has PyTorch 2.5 support.
I have prepared a cherry pick branch for a 2.6.4 that is the minimal change over 2.6.3 …
=> [Fix] Use CUDA 12.4 in the build system so that the current build system stops failing

flash_attn/ops/activations.py
The return type of `swiglu_bwd_codestring` is incorrect, (specifies `T` not `void` despite the lack of returned value). While it doesn't appear to have an impact in CUDA, it does have an adverse effect in ROCm, resulting in incorrect gradients. Changing it to `void` resolves the issue.
=> Fix swiglu backwards return type

csrc/flash_attn/src/flash_bwd_kernel.h
dtanh is not used when Is_softcap=false. Resulting warnings are quite noisy during compile.
=> flash_bwd_kernel.h: add maybe_unused annotation to suppress compile warnings

hopper/copy_paged_sm90_tma_cutlass35.hpp, hopper/copy_paged_sm90_tma_cutlass36.hpp, hopper/mainloop_fwd_sm90_tma_gmma_ws.hpp
This fixes an issue in the varlen Flash Attention 3 Varlen Kernel, leading ptxas to serialize wgmma instructions, obviously having a drastic performance impact that was hidden by the fact that varlen performance is still better in the degraded version than in the non-varlen case
With this fix, ptxas build warnings like this are gone: "ptxas info    : ([C7510](https://www.internalfb.com/cases/7510)) Potential Performance Loss: wgmma.mma_async instructions are serialized due to wgmma pipeline crossing function boundary ..."  and the performance for FA3 varlen kernels improves drastically in benchmarks. ( non-public ) - Overall, performance improved almost 2 x in some edge cases with these changes. 
Approach:
* Use less registers or use registers for a shorter amount of steps than previously …
=> Fix FA3 Varlen Performance regression

csrc/flash_attn/flash_api.cpp, csrc/flash_attn_ck/mha_bwd.cpp, csrc/flash_attn_ck/mha_fwd.cpp, csrc/flash_attn_ck/mha_fwd_kvcache.cpp, csrc/flash_attn_ck/mha_varlen_bwd.cpp, csrc/flash_attn_ck/mha_varlen_fwd.cpp, csrc/ft_attention/ft_attention.cpp, csrc/fused_dense_lib/fused_dense.cpp, csrc/layer_norm/ln_api.cpp, csrc/rotary/rotary.cpp, csrc/xentropy/xentropy_kernel.cu, hopper/flash_api.cpp
While compiling with clang-17 on ARM64
```
FAILED: /home/sclarkson/flash-attention/build/temp.linux-aarch64-3.10/csrc/flash_attn/flash_api.o 
clang++-17 -MMD -MF /home/sclarkson/flash-attention/build/temp.linux-aarch64-3.10/csrc/flash_attn/flash_api.o.d -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/sclarkson/flash-attention/csrc/flash_attn -I/home/sclarkson/flash-attention/csrc/flash_attn/src -I/home/sclarkson/flash-attention/csrc/cutlass/include -I/usr/lib/python3/dist-packages/torch/include -I/usr/lib/python3/dist-packages/torch/include/torch/csrc/api/include …
```
=> Fix compilation with clang on ARM64

README.md
I've had this issue and also seen many people questioning how to use FA3.
usually people try to 
`import as flash_attn.hopper `
or as
`import flashattn_hopper
`
but it should be 
`import flash_attn_interface`
=> Add how to import FA3 to documentation.

flash_attn/flash_attn_interface.py
In inference mode, we don't need to save the inputs/outputs used by the training mode. This PR can reduce memory usage during LLM serving(such as vllm, it uses those flash attn APIs for a better performance).
=> don't save inputs/outputs buffer of FlashAttenFunc to reduce memory usage for inference mode

flash_attn/flash_attn_interface.py
PyTorch automatically disables gradient inside a custom autograd function, thus the call to `torch.is_grad_enabled()` always returns `False`. This PR moves the call to the wrapper function instead.
=> Fix calls to `torch.is_grad_enabled()`

flash_attn/flash_attn_interface.py
When is_grad is false, the variable out does not exist.
=> fix bug when is_grad is false

hopper/benchmark_flash_attention_fp8.py
Updates an incorrect torch dtype.
I don't think this is consequential but I noticed it when skimming the code.
=> Fix incorrect torch dtype

benchmarks/benchmark_gemm.py
A simple adjustment of a few lines in `benchmarks/benchmark_gemm.py` to output hipBLAS vs cuBLAS for more accurate reporting.
=> Add hipBLAS/cuBLAS distinction in benchmark_gemm.py

flash_attn/flash_attn_interface.py
There are certain workloads where we use these internal functions directly and it is useful for us to have this argument exposed as a kwarg. The default behavior remains the same.
=> Expose `zero_tensors` arg in varlen functions

MANIFEST.in, setup.py
Currently, the source distribution contains only sources needed for CUDA builds (it's missing `csrc/composable_kernel`). Fix that, and while at it clean up some logic in `setup.py`. More specifically:
- always update both submodules when inside the git repo, so that they are both included in sdist
- add missing `.py` files to sdist
- run `git submodule ...` commands only when inside the git repo; otherwise (e.g. when installing from sdist), just verify that the submodules were checked out, and issue a more explanatory error if they weren't
- use `subprocess.run()` throughout to run commands, and check their return status
=> Support ROCM builds from source distribution, and improve error handling

.github/workflows/publish.yml
This updates `setuptools` version used in the build pipeline to v75.8.0, which includes https://github.com/pypa/setuptools/commit/f285d01e2661b01e4947a4dca7704790b65f2967 and generates `Metadata: 2.2` manifests for pypi
With this change, it becomes easier to manage flash-attn installation with `uv`. See https://github.com/astral-sh/uv/pull/6607#issuecomment-2308931562
>> for some reason, uv always tries to build flash-attn during sync, even though it was not requested
>
>This is expected _and_ required. `flash-attn` ships as a source distribution, and only at `Metadata-Version: 2.1`, so you _must_ ask the build backend for its dependencies per the spec -- which in turn requires that its build dependencies are already installed. There's really nothing we can do about this -- it's a problem …
=> [Build] Update version of setuptools used to generate core package

hopper/flash_api.cpp, hopper/flash_fwd_launch_template.h
Adding an MLA feature allows ropeDim=64 and latentDim=512, and updates conditional checks in flash_api.cpp to handle MLA-enabled paths.
=> Enable MLA flag in FA3 (rope=64, latent=512)

csrc/flash_attn/src/flash_fwd_kernel.h
This project uses c++17 which still has this requirement.
=> fix: add "typename" prior to dependent type name

hopper/mainloop_fwd_sm90_tma_gmma_ws.hpp
Building using CUDA 12.1 was resulting in:
```
.../hopper/mainloop_fwd_sm90_tma_gmma_ws.hpp(1068): error: no operator "=" matches these operands
operand types are: cutlass::bfloat16_t = float
sScale(get<0>(taccOcO_row(mi)), stage) = scales(mi);
```
which appears to be from slight differences in template type deduction
=> Fix CUDA 12.1 build

csrc/flash_attn/src/flash_bwd_kernel.h, csrc/flash_attn/src/flash_bwd_preprocess_kernel.h
When using Flash Attention, if the batch size is relatively large, say 10k or 15k, an "illegal memory access" error will occur. Eventually, it turns out that the issue stems from `row_offset_dq_accum`  numerical  overflow during the backward of Flash Attention.
=> fix: promote index to type longlong to avoid numerical overflow

flash_attn/ops/triton/layer_norm.py
Generate a list of autotune configs based on device warp size to avoid triton error if maximum threads per block is exceeded. This fixes an issue seen when running the Huggingface Nanotron tiny llama example on an AMD Instinct device, as the current implementation passes an autotune config with 32 warps which surpasses 1024 threads per block on devices with warp size 64.
=> Triton autotune configs for devices with warp size != 32

hopper/tile_scheduler.hpp
It throws build error. num_head -> args.num_head to fix that.
=> [Easy] fix num_head reference in tile_scheduler.hpp

hopper/setup.py
In certain environments the relative path to the vendored nvcc is not picked up correctly if provided relative. In this PR, I just make it absolute.
=> Make hopper build more robust

hopper/epilogue_bwd.hpp, hopper/flash_api.cpp, hopper/flash_attn_interface.py, hopper/flash_bwd_launch_template.h, hopper/mainloop_bwd_sm80.hpp, hopper/mainloop_bwd_sm90_tma_gmma_ws.hpp, hopper/test_flash_attn.py
Recently, there are cases where ~~hdimQK >= hdimV~~ hdimQK != hdimV, such as DeepSeek (#1487).
So we worked on a simple trick (rounding hdimQK and hdimV to the same value) to support that configuration in the backward kernel as well.
Of course, it would be best to tile K and V with different rounding values (which we're working on internally), but this implementation allows us to skip explicit padding & unpadding hdimV, resulting in a performance improvement of about 15%.
This feature was developed for internal use at @kakao.
=> Support hdimQK != hdimV backward

setup.py
In this PR
1. Update backend (composable kernel)
2. Detect AMD hardware explicitly, because some version of hipcc does not support arch=native
=> [AMD ROCm] Update backend to improve performance

hopper/flash_api.cpp, hopper/flash_attn_interface.py, hopper/setup.py, hopper/test_flash_attn.py
This should enable us to build a single wheel for all python versions
(still requires a different build per OS/PyTorch version)
=> [fa3] Use Python stable ABI

hopper/flash_api.cpp
Those changes are necessary to build on windows, as MSVC does not like `#ifdefs` inside preprocessor macro arguments.
=> [fa3] Some fixes for windows build

setup.py, tests/test_flash_attn_ck.py
1. This PR update the CK to fix the compilation issue on gfx942
2. Enables users to build additional kernels by controlling the optdim parameter.
3. Increases the threshold of test_flash_attn_bwd_overflow to prevent test failures on gfx950.
=> [AMD ROCm] Fix compilation issue in gfx942

.github/workflows/publish.yml
Pytorch2.8 released a day or two ago.
Untested PR, noticed build issues in GH Issues.
=> feat: add support for pytorch2.8

hopper/flash_api.cpp
When testing the deterministic option for the GQA case, we found it fell into deadlock issues. Initialization dk and dv_semaphore to zeros to fix this issue.
=> Update the initialization of dk/dv_semaphore

hopper/tile_scheduler.hpp
Hi,
I was trying to run FA3 with seqlen of 4M tokens and I encounter a Floating Point Exception error due to int32 overflow for the parameters storing the tensor sizes. 
I have casted them to long to avoid this issue.
Thanks @tridao for the suggestion!
=> FA3 tensor size parameter fix for long context len (seqlen >=4M)

.github/workflows/_build.yml, .github/workflows/publish.yml
This PR tries to only move the build-wheel logic into a workflow template. 
A few noticeable changes:
Instead of re-checking for the version number in the build job (by parsing `GITHUB_REF`), I'm suggesting to extract the version once in `setup_release` and pass it downstream to follow up tasks (`needs.setup_release.outputs.release-version`). 
This allows to passing the release-version as input into the workflow template and to change:
```
- name: Get Release with tag
id: get_current_release
uses: joutvhu/get-release@v1
with:
tag_name: ${{ inputs.release-version }}
```
=> ci: Move build job to workflow template

flash_attn/cute/flash_fwd.py
The purpose of this PR is twofold: 
1. to add support for `mma_pv_is_rs == False`, which is currently always set to `True`
2. to allow 3 mma warp groups, thus enabling `m_block_size == 192`, and as a result head dimension 96. 
Currently, the kernel hangs with `m_block_size == 192` due to launching too few threads per block and attempting to allocate too many registers. This fix puts the CuTe DSL kernel in line with the C++ version; see e.g. [the register allocation logic here.](https://github.com/ColfaxResearch/flash-attention/blob/3268c04b81d16f4a94a50dfffdd879c3222e71aa/hopper/flash_fwd_kernel_sm90.h#L82)
=> [FIX] Allow m_block_size == 192 and mma_pv_is_rs == False in Sm90 CuTe DSL

hopper/sm90_pipeline_no_cluster.hpp
@tridao Fix CUDA barrier init crash when num_consumers < NumThreadsPerWarpGroup
Previously, integer division caused num_consumer_warpgroups_per_cluster to be 0 when params.num_consumers (e.g., 32) was less than NumThreadsPerWarpGroup (128), leading to a compiler failure during barrier initialization. Changed to round-up division to ensure a minimum value of 1.
=> [BUG] CUDA 13: make FA3 compatible with CUDA 13 Builds

flash_attn/cute/block_info.py, flash_attn/cute/flash_bwd_postprocess.py, flash_attn/cute/flash_bwd_sm90.py, flash_attn/cute/hopper_helpers.py, flash_attn/cute/named_barrier.py
FlashAttention backward for SM90 in CuTe-DSL. 
* Main kernel `flash_attn/cute/flash_bwd_sm90.py`
* Minor updates `block_info.py`, `named_barrier.py`
* Postprocessing kernel for SM90 `flash_bwd_postprocess.py`, 
* Inline PTX func added for TMA cpasync bulk reduce atomic add for dQaccum `hopper_helpers.py`
Compared to torch reference in FP32 (QKV initialized in BF16)
```python
q32, k32, v32 = [t.detach().float().requires_grad_(True) for t in (Q, K, V)]
out32 = torch.einsum(
'bmhn,bnhd->bmhd',
torch.softmax(torch.einsum('bmhd,bnhd->bmhn', q32, k32) * softmax_scale, dim=-1),
v32,
)
dQ_torch, dK_torch, dV_torch = torch.autograd.grad(out32, (q32, k32, v32), dO.float(), retain_graph=True)
torch.testing.assert_close(dQ_torch, dQ, rtol=1e-3, atol=0.0625,  check_dtype=False) …
```
=> flash-attn-cute bwd sm90
