csrc/flash_attn/fmha_api.cpp
=> fix typo in function mha_fwd

.gitignore, MANIFEST.in, Makefile, setup.py
should allow you to upload this to pypi
```bash
$ pip install twine
```
then
```bash
$ make upload_package
```
it will then ask for username and password, which you need to acquire by making an account at https://pypi.org/
=> allow for uploading to pypi

training/configs/callbacks/default.yaml
=> fix typo in default.yaml

README.md
Hopefully this will help people learn how to use FlashAttention (e.g. at first I had similar questions to the person in https://github.com/HazyResearch/flash-attention/issues/70)
Cheers!
=> Add a simple tutorial to README.md

usage.md
Add paddlepaddle integration in usage.md.
=> add paddlepaddle in usage

csrc/layer_norm/ln_api.cpp
=> [LayerNorm] Fix typo in ln_api.cpp

flash_attn/models/bert.py
Tiny change that allows Bert models to use rotary embeddings. Please let me know if the style is different to what you prefer.
=> Small PR to allow rotary embeddings for Bert

flash_attn/__init__.py, training/Dockerfile
This is so that we can grab in the latest features including #386 from PyPI
=> Request for v2.0.2

setup.py
=> fix binary wheel installation when nvcc is not available

flash_attn/models/gpt.py, flash_attn/modules/mha.py, flash_attn/ops/fused_dense.py, flash_attn/utils/distributed.py, tests/models/test_llama.py
=> support when num_heads is not divisible by world_size; resolves #459

benchmarks/benchmark_flash_attention.py
as mentioned in https://github.com/facebookresearch/xformers/issues/832
=> add benchmark for xformers fa2 wrapper

flash_attn/models/llama.py
Requires the other PRs to work well:
https://github.com/Dao-AILab/flash-attention/pull/490
https://github.com/Dao-AILab/flash-attention/pull/488
LLaMa2 notably adds MQA
=> [decoding] Support LLaMa2 and CodeLLaMa

csrc/flash_attn/src/utils.h
These used to be used but aren't anymore. We might as well remove them.
=> Remove old code in utils.h

flash_attn/modules/mha.py
https://github.com/Dao-AILab/flash-attention/issues/746
=> Fix: implement deterministic backward in mha

flash_attn/losses/cross_entropy.py, flash_attn/ops/triton/cross_entropy.py, tests/losses/test_cross_entropy.py
If `return_z_loss` is True, return how much z_loss contributed to the overall loss.
=> Add ability to return z_loss component of overall loss

csrc/ft_attention/setup.py, csrc/fused_dense_lib/setup.py, csrc/fused_softmax/setup.py, csrc/layer_norm/setup.py, csrc/rotary/setup.py, csrc/xentropy/setup.py, setup.py
My build environment kept using high cpu and was getting killed trying to compile fused_dense_lib.
=> Make nvcc threads configurable via environment variable

setup.py
When timeout connecting, you get URLError: <urlopen error timed out>, In that case, build it from source.
=> add exception to Timeout Error

tests/test_flash_attn.py
these assert is always true in `test_flash_attn_varlen_deterministic`, I modify it like `test_flash_attn_deterministic`
=> Fix the varlen deterministic test

flash_attn/flash_attn_interface.py
This is helpful for combining flash attention with ring attention.
=> Add return_softmax_lse in flash_attn_with_kvcache

hopper/benchmark_attn.py
=> Add cudnn benchmark for var-len

hopper/benchmark_attn.py, hopper/epilogue_fwd_sm90_tma.hpp
Benchmarks:
+ bwd benchmarks: var-seq-len with cudnn and fav3
Small fixes:
* Set -infinity to LSE;
=> bwd benchmark + small fixes

hopper/epilogue_fwd_sm90_tma.hpp, hopper/flash_fwd_kernel.h, hopper/test_flash_attn.py, tests/test_util.py
ATT, this PR fixed out-of-bound writes for var-seq-len zero-length KVs. Also added unittests.
=> Fix out-of-bound writes for var-seq-len zero-length KVs

flash_attn/__init__.py, setup.py
This PR adds the compilation flags necessary for support on blackwell. It also updates the version so that dependencies can check against it easily.
=> Blackwell support

flash_attn/__init__.py
Version update awaiting further testing and merge of #1436
=> Change version to 2.7.3

.github/workflows/publish.yml
Early PR to be ready for torch2.7 release.
Torch2.6 supports upto cuda 12.6
=> feat: add support for torch2.7

setup.py
Add missing compile flag for CK backend
=> [AMD ROCm] Change compile flag for CK

csrc/flash_attn_ck/flash_common.cpp, csrc/flash_attn_ck/flash_common.hpp, setup.py
Composable kernel use some deprecated intrinsic, which make compile error in ROCm7.
We update the submodule in this PR.
=> [AMD ROCm] Fix intrinsic for ROCm7

flash_attn/cute/utils.py
=> [Cute] Remove trailing bracket

hopper/flash_attn_interface.py, hopper/test_flash_attn.py
Allow outputting the lse via a kwarg `return_attn_probs` just as in FA2 currently
cc @tridao
=> [`FA3`] Allow returning LSE via kwarg

benchmarks/benchmark_attn.py, hopper/benchmark_attn.py
For local attention, there is a typo that is subtracting window_size[1] instead of adding. This diff tries to fix that.
=> Fix typo in flops calculation for local attention
